CREATE TABLE "FichaServidor" (
  "id" serial NOT NULL ,
  "cpf" varchar(255) COLLATE "pg_catalog"."default",
  "nome" varchar(255) COLLATE "pg_catalog"."default",
  "dataNascimento" date,
  "estadoCivil" varchar(255) COLLATE "pg_catalog"."default",
  "email" varchar(255) COLLATE "pg_catalog"."default",
  "tipoTelefone" varchar(255) COLLATE "pg_catalog"."default",
  "telefone" varchar(255) COLLATE "pg_catalog"."default",
  "lotacao" varchar(255) COLLATE "pg_catalog"."default",
  "cargo" varchar(255) COLLATE "pg_catalog"."default",
  "tipoEndereco" varchar(255) COLLATE "pg_catalog"."default",
  "cep" varchar(255) COLLATE "pg_catalog"."default",
  "pais" varchar(255) COLLATE "pg_catalog"."default",
  "estado" varchar(255) COLLATE "pg_catalog"."default",
  "municipio" varchar(255) COLLATE "pg_catalog"."default",
  "tipoLogradouro" varchar(255) COLLATE "pg_catalog"."default",
  "logradouro" varchar(255) COLLATE "pg_catalog"."default",
  "numero" varchar(255) COLLATE "pg_catalog"."default",
  "bairro" varchar(255) COLLATE "pg_catalog"."default",
  "complemento" varchar(255) COLLATE "pg_catalog"."default",
  "possuiImovelProprio" bool,
  "moraOcupacaoIrregular" bool,
  "resideAreaRisco" bool,
  "tempoServicoServidor" varchar(255) COLLATE "pg_catalog"."default",
  "possuiMaisMatriculas" bool,
  "participouProgramaHabitacional" bool,
  "rendaFamiliar" varchar(255) COLLATE "pg_catalog"."default",
  "possuiDeficiencia" bool,
  "nomeDeficiencia" varchar(255) COLLATE "pg_catalog"."default",
  "codigoDeficiencia" varchar(255) COLLATE "pg_catalog"."default",
  "membroFamiliaPossuiDeficiencia" bool,
  "membroFamiliaNomeDeficiencia" varchar(255) COLLATE "pg_catalog"."default",
  "membroFamiliaCodigoDeficiencia" varchar(255) COLLATE "pg_catalog"."default",
  "possuiDoencaFamilia" bool,
  "nomeDoencaFamilia" varchar(255) COLLATE "pg_catalog"."default",
  "matriculas" varchar(255) COLLATE "pg_catalog"."default",
  CONSTRAINT "cadastroServidor_pkey" PRIMARY KEY ("id")
)
WITH (OIDS=TRUE)
;

