-- MySQL Script generated by MySQL Workbench
-- sáb 30 mar 2019 22:05:44 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_jubarte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_jubarte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_jubarte` ;
USE `db_jubarte` ;

-- -----------------------------------------------------
-- Table `db_jubarte`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_jubarte`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(95) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_jubarte`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_jubarte`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categorie_id` INT NULL,
  `title` VARCHAR(45) NULL,
  `text` LONGTEXT NULL,
  `updated_at` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tasks_categories_idx` (`categorie_id` ASC),
  CONSTRAINT `fk_tasks_categories`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `db_jubarte`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_jubarte`.`categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_jubarte`;
INSERT INTO `db_jubarte`.`categories` (`id`, `name`) VALUES (1, 'Departamento Pessoal');
INSERT INTO `db_jubarte`.`categories` (`id`, `name`) VALUES (2, 'Recursos Humanos');
INSERT INTO `db_jubarte`.`categories` (`id`, `name`) VALUES (3, 'Funcionarios');
INSERT INTO `db_jubarte`.`categories` (`id`, `name`) VALUES (4, 'Financeiro');
INSERT INTO `db_jubarte`.`categories` (`id`, `name`) VALUES (5, 'Obras');

COMMIT;

